global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus.logs:9090']

  - job_name: 'loki'
    static_configs:
      - targets: ['gateway.logs:3100']
